//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EU.CqrXs.Srv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EU.CqrXs.Srv.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string action_about {
            get {
                return ResourceManager.GetString("action_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string action_continue {
            get {
                return ResourceManager.GetString("action_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string action_exit {
            get {
                return ResourceManager.GetString("action_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string action_help {
            get {
                return ResourceManager.GetString("action_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game.
        /// </summary>
        internal static string action_load {
            get {
                return ResourceManager.GetString("action_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string action_options {
            get {
                return ResourceManager.GetString("action_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game.
        /// </summary>
        internal static string action_save {
            get {
                return ResourceManager.GetString("action_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot.
        /// </summary>
        internal static string action_screenshot {
            get {
                return ResourceManager.GetString("action_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string action_start {
            get {
                return ResourceManager.GetString("action_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string action_stop {
            get {
                return ResourceManager.GetString("action_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudio 2022 C# 4.8.
        /// </summary>
        internal static string build_with {
            get {
                return ResourceManager.GetString("build_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/area23.at/.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area23.at by Heinrich Elsigan (heinrich.elsigan@area23.at).
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tDbg_text {
            get {
                return ResourceManager.GetString("tDbg_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.24.928.
        /// </summary>
        internal static string version_name {
            get {
                return ResourceManager.GetString("version_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/area23.at/wiki.
        /// </summary>
        internal static string wiki_uri {
            get {
                return ResourceManager.GetString("wiki_uri", resourceCulture);
            }
        }
    }
}
