@echo off

"C:\Users\heinr\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\9.0.5\tools\crossgen2.exe" --targetos:windows --targetarch:x64 -O --composite  --out:"C:\Users\heinr\source\chat-ipv6\C#\EU.CqrXs.WinForm.SecureChat\obj\Release\net9.0-windows\win-x64\R2R\EU.CqrXs.WinForm.SecureChat.r2r.dll" C:\Users\heinr\.nuget\packages\bouncycastle.cryptography\2.5.1\lib\net6.0\BouncyCastle.Cryptography.dll
C:\Users\heinr\.nuget\packages\microsoft.bcl.timeprovider\9.0.4\lib\net8.0\Microsoft.Bcl.TimeProvider.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.caching.abstractions\9.0.3\lib\net9.0\Microsoft.Extensions.Caching.Abstractions.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.caching.memory\9.0.3\lib\net9.0\Microsoft.Extensions.Caching.Memory.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.caching.stackexchangeredis\9.0.2\lib\net9.0\Microsoft.Extensions.Caching.StackExchangeRedis.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\9.0.3\lib\net9.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.logging.abstractions\9.0.3\lib\net9.0\Microsoft.Extensions.Logging.Abstractions.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.objectpool\9.0.4\lib\net9.0\Microsoft.Extensions.ObjectPool.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.options\9.0.3\lib\net9.0\Microsoft.Extensions.Options.dll
C:\Users\heinr\.nuget\packages\microsoft.extensions.primitives\9.0.3\lib\net9.0\Microsoft.Extensions.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.identitymodel.abstractions\8.8.0\lib\net9.0\Microsoft.IdentityModel.Abstractions.dll
C:\Users\heinr\.nuget\packages\microsoft.identitymodel.logging\8.8.0\lib\net9.0\Microsoft.IdentityModel.Logging.dll
C:\Users\heinr\.nuget\packages\microsoft.identitymodel.protocols.wstrust\6.8.0\lib\netstandard2.0\Microsoft.IdentityModel.Protocols.WsTrust.dll
C:\Users\heinr\.nuget\packages\microsoft.identitymodel.tokens\8.8.0\lib\net9.0\Microsoft.IdentityModel.Tokens.dll
C:\Users\heinr\.nuget\packages\microsoft.identitymodel.tokens.saml\8.2.0\lib\net9.0\Microsoft.IdentityModel.Tokens.Saml.dll
C:\Users\heinr\.nuget\packages\microsoft.identitymodel.xml\8.8.0\lib\net9.0\Microsoft.IdentityModel.Xml.dll
C:\Users\heinr\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll
C:\Users\heinr\.nuget\packages\nlog\5.4.0\lib\netstandard2.0\NLog.dll
C:\Users\heinr\.nuget\packages\pipelines.sockets.unofficial\2.2.8\lib\net5.0\Pipelines.Sockets.Unofficial.dll
C:\Users\heinr\.nuget\packages\qrcoder.core\1.0.3\lib\net8.0-windows7.0\QRCoder.Core.dll
C:\Users\heinr\.nuget\packages\sharpziplib\1.4.2\lib\net6.0\ICSharpCode.SharpZipLib.dll
C:\Users\heinr\.nuget\packages\stackexchange.redis\2.8.31\lib\net8.0\StackExchange.Redis.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.federation\8.1.2\lib\netstandard2.0\System.ServiceModel.Federation.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.http\8.1.2\lib\net8.0\System.ServiceModel.Http.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.netframingbase\8.1.2\lib\net8.0\System.ServiceModel.NetFramingBase.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.netnamedpipe\8.1.2\lib\net8.0\System.ServiceModel.NetNamedPipe.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.nettcp\8.1.2\lib\net8.0\System.ServiceModel.NetTcp.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.primitives\8.1.2\lib\net8.0\System.ServiceModel.Duplex.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.primitives\8.1.2\lib\net8.0\System.ServiceModel.Primitives.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.primitives\8.1.2\lib\net8.0\System.ServiceModel.Security.dll
C:\Users\heinr\.nuget\packages\system.servicemodel.primitives\8.1.2\lib\net8.0\System.ServiceModel.dll
C:\Users\heinr\source\chat-ipv6\C#\Area23.At.Framework\Area23.At.Framework.Core\bin\Release\net9.0-windows\Area23.At.Framework.Core.dll
C:\Users\heinr\source\chat-ipv6\C#\EU.CqrXs.WinForm.SecureChat\obj\Release\net9.0-windows\win-x64\EU.CqrXs.WinForm.SecureChat.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.CSharp.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.VisualBasic.Core.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.Win32.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.Win32.Registry.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.AppContext.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Buffers.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Collections.Concurrent.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Collections.Immutable.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Collections.NonGeneric.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Collections.Specialized.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Collections.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ComponentModel.Annotations.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ComponentModel.DataAnnotations.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ComponentModel.EventBasedAsync.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ComponentModel.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ComponentModel.TypeConverter.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ComponentModel.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Configuration.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Console.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Core.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Data.Common.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Data.DataSetExtensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Data.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.Contracts.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.Debug.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.DiagnosticSource.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.FileVersionInfo.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.Process.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.StackTrace.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.TextWriterTraceListener.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.Tools.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.TraceSource.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.Tracing.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Drawing.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Dynamic.Runtime.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Formats.Asn1.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Formats.Tar.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Globalization.Calendars.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Globalization.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Globalization.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Compression.Brotli.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Compression.FileSystem.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Compression.ZipFile.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Compression.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.FileSystem.AccessControl.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.FileSystem.DriveInfo.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.FileSystem.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.FileSystem.Watcher.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.FileSystem.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.IsolatedStorage.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.MemoryMappedFiles.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Pipelines.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Pipes.AccessControl.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Pipes.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.UnmanagedMemoryStream.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Linq.Expressions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Linq.Parallel.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Linq.Queryable.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Linq.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Memory.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Http.Json.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Http.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.HttpListener.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Mail.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.NameResolution.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.NetworkInformation.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Ping.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Quic.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Requests.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Security.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.ServicePoint.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.Sockets.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.WebClient.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.WebHeaderCollection.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.WebProxy.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.WebSockets.Client.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.WebSockets.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Net.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Numerics.Vectors.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Numerics.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ObjectModel.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Private.CoreLib.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Private.DataContractSerialization.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Private.Uri.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Private.Xml.Linq.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Private.Xml.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.DispatchProxy.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.Emit.ILGeneration.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.Emit.Lightweight.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.Emit.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.Metadata.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.TypeExtensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Reflection.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Resources.Reader.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Resources.ResourceManager.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Resources.Writer.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.CompilerServices.Unsafe.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.CompilerServices.VisualC.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Handles.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.InteropServices.JavaScript.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.InteropServices.RuntimeInformation.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.InteropServices.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Intrinsics.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Loader.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Numerics.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Serialization.Formatters.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Serialization.Json.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Serialization.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Serialization.Xml.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.Serialization.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Runtime.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.AccessControl.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Claims.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Algorithms.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Cng.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Csp.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Encoding.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.OpenSsl.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.X509Certificates.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Principal.Windows.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Principal.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.SecureString.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ServiceModel.Web.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ServiceProcess.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Text.Encoding.CodePages.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Text.Encoding.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Text.Encoding.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Text.Encodings.Web.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Text.Json.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Text.RegularExpressions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Channels.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Overlapped.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Tasks.Dataflow.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Tasks.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Tasks.Parallel.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Tasks.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Thread.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.ThreadPool.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.Timer.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Transactions.Local.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Transactions.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.ValueTuple.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Web.HttpUtility.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Web.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.Linq.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.ReaderWriter.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.Serialization.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.XDocument.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.XPath.XDocument.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.XPath.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.XmlDocument.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.XmlSerializer.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xml.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\mscorlib.dll
C:\Users\heinr\.nuget\packages\microsoft.netcore.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\netstandard.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Accessibility.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\DirectWriteForwarder.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.VisualBasic.Forms.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.VisualBasic.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.Win32.Registry.AccessControl.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\Microsoft.Win32.SystemEvents.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationCore.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework-SystemCore.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework-SystemData.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework-SystemDrawing.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework-SystemXml.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework-SystemXmlLinq.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.Aero.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.Aero2.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.AeroLite.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.Classic.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.Fluent.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.Luna.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.Royale.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationFramework.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\PresentationUI.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\ReachFramework.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.CodeDom.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Configuration.ConfigurationManager.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Design.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.EventLog.Messages.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.EventLog.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Diagnostics.PerformanceCounter.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.DirectoryServices.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Drawing.Common.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Drawing.Design.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Drawing.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Formats.Nrbf.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.IO.Packaging.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Printing.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Private.Windows.Core.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Resources.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Pkcs.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.ProtectedData.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Cryptography.Xml.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Security.Permissions.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Threading.AccessControl.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Controls.Ribbon.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Extensions.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Forms.Design.Editors.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Forms.Design.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Forms.Primitives.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Forms.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Input.Manipulations.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Windows.Presentation.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\System.Xaml.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\UIAutomationClient.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\UIAutomationClientSideProviders.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\UIAutomationProvider.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\UIAutomationTypes.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\WindowsBase.dll
C:\Users\heinr\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\9.0.5\runtimes\win-x64\lib\net9.0\WindowsFormsIntegration.dll
