//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Area23.At.Framework.Library.Static;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace Area23.At.Framework.Library.Cqr
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CqrServiceSoap",
          Namespace = "https://srv.cqrxs.eu/v1.6/")]
    public partial class CqrService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        /// <remarks/>
        public CqrService()
        {
            this.Url = LibPaths.CqrServiceSoap;
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/Send1StSrvMsg",
              RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send1StSrvMsg(string cryptMsg)
        {
            object[] results = this.Invoke("Send1StSrvMsg", new object[] {
                    cryptMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSend1StSrvMsg(string cryptMsg, System.AsyncCallback
              callback, object asyncState)
        {
            return this.BeginInvoke("Send1StSrvMsg", new object[] {
                    cryptMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndSend1StSrvMsg(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/ChatRoomInvite",
              RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChatRoomInvite(string cryptMsg)
        {
            object[] results = this.Invoke("ChatRoomInvite", new object[] {
                    cryptMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChatRoomInvite(string cryptMsg, System.AsyncCallback
              callback, object asyncState)
        {
            return this.BeginInvoke("ChatRoomInvite", new object[] {
                    cryptMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndChatRoomInvite(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/ChatPollAll", RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChatPollAll(string cryptMsg)
        {
            object[] results = this.Invoke("ChatPollAll", new object[] {
                    cryptMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChatPollAll(string cryptMsg, System.AsyncCallback callback,
              object asyncState)
        {
            return this.BeginInvoke("ChatPollAll", new object[] {
                    cryptMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndChatPollAll(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/ChatRoomPoll",
              RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChatRoomPoll(string cryptMsg)
        {
            object[] results = this.Invoke("ChatRoomPoll", new object[] {
                    cryptMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChatRoomPoll(string cryptMsg, System.AsyncCallback callback,
              object asyncState)
        {
            return this.BeginInvoke("ChatRoomPoll", new object[] {
                    cryptMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndChatRoomPoll(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/ChatRoomPush",
              RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChatRoomPush(string cryptMsg)
        {
            object[] results = this.Invoke("ChatRoomPush", new object[] {
                    cryptMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChatRoomPush(string cryptMsg, System.AsyncCallback callback,
              object asyncState)
        {
            return this.BeginInvoke("ChatRoomPush", new object[] {
                    cryptMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndChatRoomPush(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/ChatRoomClose",
              RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChatRoomClose(string cryptMsg)
        {
            object[] results = this.Invoke("ChatRoomClose", new object[] {
                    cryptMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginChatRoomClose(string cryptMsg, System.AsyncCallback
              callback, object asyncState)
        {
            return this.BeginInvoke("ChatRoomClose", new object[] {
                    cryptMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndChatRoomClose(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/TestService", RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestService()
        {
            object[] results = this.Invoke("TestService", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTestService(System.AsyncCallback callback, object
              asyncState)
        {
            return this.BeginInvoke("TestService", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndTestService(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/GetIPAddress",
              RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetIPAddress()
        {
            object[] results = this.Invoke("GetIPAddress", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetIPAddress(System.AsyncCallback callback, object
              asyncState)
        {
            return this.BeginInvoke("GetIPAddress", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetIPAddress(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/TestCache", RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestCache()
        {
            object[] results = this.Invoke("TestCache", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTestCache(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("TestCache", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndTestCache(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/GetKey", RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKey(string key)
        {
            object[] results = this.Invoke("GetKey", new object[] {
                    key});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetKey(string key, System.AsyncCallback callback, object
              asyncState)
        {
            return this.BeginInvoke("GetKey", new object[] {
                    key}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetKey(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute(
             "https://srv.cqrxs.eu/v1.6/ResetCache", RequestNamespace = "https://srv.cqrxs.eu/v1.6/",
              ResponseNamespace = "https://srv.cqrxs.eu/v1.6/",
              Use = System.Web.Services.Description.SoapBindingUse.Literal,
              ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResetCache()
        {
            object[] results = this.Invoke("ResetCache", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginResetCache(System.AsyncCallback callback, object
              asyncState)
        {
            return this.BeginInvoke("ResetCache", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndResetCache(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }

}