//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace EU.CqrXs.CqrSrv.CqrJd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://cqrjd.eu/cqrsrv/cqrjd/", ConfigurationName="EU.CqrXs.CqrSrv.CqrJd.CqrServiceSoap")]
    public interface CqrServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/Send1StSrvMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Send1StSrvMsg(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/Send1StSrvMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Send1StSrvMsgAsync(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/SendValidatedSrvMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendValidatedSrvMsg(System.Guid from, System.Guid to, string cryptMsgSrv, string cryptMsgPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/SendValidatedSrvMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendValidatedSrvMsgAsync(System.Guid from, System.Guid to, string cryptMsgSrv, string cryptMsgPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/SendSrvMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSrvMsg(string cryptMsgSrv, string cryptMsgPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/SendSrvMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSrvMsgAsync(string cryptMsgSrv, string cryptMsgPartner);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomInvite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChatRoomInvite(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomInvite", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChatRoomInviteAsync(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomPoll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChatRoomPoll(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomPoll", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChatRoomPollAsync(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomPushMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChatRoomPushMessage(string cryptMsg, string chatRoomMembersCrypted);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomPushMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChatRoomPushMessageAsync(string cryptMsg, string chatRoomMembersCrypted);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomClose", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChatRoomClose(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/ChatRoomClose", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChatRoomCloseAsync(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/UpdateContacts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateContacts(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/UpdateContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateContactsAsync(string cryptMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/TestService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestService();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cqrjd.eu/cqrsrv/cqrjd/TestService", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CqrServiceSoapChannel : EU.CqrXs.CqrSrv.CqrJd.CqrServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CqrServiceSoapClient : System.ServiceModel.ClientBase<EU.CqrXs.CqrSrv.CqrJd.CqrServiceSoap>, EU.CqrXs.CqrSrv.CqrJd.CqrServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CqrServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CqrServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CqrServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CqrServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CqrServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CqrServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CqrServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CqrServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Send1StSrvMsg(string cryptMsg)
        {
            return base.Channel.Send1StSrvMsg(cryptMsg);
        }
        
        public System.Threading.Tasks.Task<string> Send1StSrvMsgAsync(string cryptMsg)
        {
            return base.Channel.Send1StSrvMsgAsync(cryptMsg);
        }
        
        public string SendValidatedSrvMsg(System.Guid from, System.Guid to, string cryptMsgSrv, string cryptMsgPartner)
        {
            return base.Channel.SendValidatedSrvMsg(from, to, cryptMsgSrv, cryptMsgPartner);
        }
        
        public System.Threading.Tasks.Task<string> SendValidatedSrvMsgAsync(System.Guid from, System.Guid to, string cryptMsgSrv, string cryptMsgPartner)
        {
            return base.Channel.SendValidatedSrvMsgAsync(from, to, cryptMsgSrv, cryptMsgPartner);
        }
        
        public string SendSrvMsg(string cryptMsgSrv, string cryptMsgPartner)
        {
            return base.Channel.SendSrvMsg(cryptMsgSrv, cryptMsgPartner);
        }
        
        public System.Threading.Tasks.Task<string> SendSrvMsgAsync(string cryptMsgSrv, string cryptMsgPartner)
        {
            return base.Channel.SendSrvMsgAsync(cryptMsgSrv, cryptMsgPartner);
        }
        
        public string ChatRoomInvite(string cryptMsg)
        {
            return base.Channel.ChatRoomInvite(cryptMsg);
        }
        
        public System.Threading.Tasks.Task<string> ChatRoomInviteAsync(string cryptMsg)
        {
            return base.Channel.ChatRoomInviteAsync(cryptMsg);
        }
        
        public string ChatRoomPoll(string cryptMsg)
        {
            return base.Channel.ChatRoomPoll(cryptMsg);
        }
        
        public System.Threading.Tasks.Task<string> ChatRoomPollAsync(string cryptMsg)
        {
            return base.Channel.ChatRoomPollAsync(cryptMsg);
        }
        
        public string ChatRoomPushMessage(string cryptMsg, string chatRoomMembersCrypted)
        {
            return base.Channel.ChatRoomPushMessage(cryptMsg, chatRoomMembersCrypted);
        }
        
        public System.Threading.Tasks.Task<string> ChatRoomPushMessageAsync(string cryptMsg, string chatRoomMembersCrypted)
        {
            return base.Channel.ChatRoomPushMessageAsync(cryptMsg, chatRoomMembersCrypted);
        }
        
        public string ChatRoomClose(string cryptMsg)
        {
            return base.Channel.ChatRoomClose(cryptMsg);
        }
        
        public System.Threading.Tasks.Task<string> ChatRoomCloseAsync(string cryptMsg)
        {
            return base.Channel.ChatRoomCloseAsync(cryptMsg);
        }
        
        public string UpdateContacts(string cryptMsg)
        {
            return base.Channel.UpdateContacts(cryptMsg);
        }
        
        public System.Threading.Tasks.Task<string> UpdateContactsAsync(string cryptMsg)
        {
            return base.Channel.UpdateContactsAsync(cryptMsg);
        }
        
        public string TestService()
        {
            return base.Channel.TestService();
        }
        
        public System.Threading.Tasks.Task<string> TestServiceAsync()
        {
            return base.Channel.TestServiceAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CqrServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CqrServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CqrServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress(ConfigurationManager.AppSettings["CqrServiceSoap"]);
            }
            if ((endpointConfiguration == EndpointConfiguration.CqrServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress(ConfigurationManager.AppSettings["CqrServiceSoap12"]);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CqrServiceSoap,
            
            CqrServiceSoap12,
        }
    }
}
