//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EU.CqrXs.WinForm.SecureChat.Properties.de {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EU.CqrXs.WinForm.SecureChat.Properties.de.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_hash {
            get {
                object obj = ResourceManager.GetObject("a_hash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_right_key {
            get {
                object obj = ResourceManager.GetObject("a_right_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddAesArrow {
            get {
                object obj = ResourceManager.GetObject("AddAesArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CableWireCut {
            get {
                object obj = ResourceManager.GetObject("CableWireCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ClickToUpload {
            get {
                object obj = ResourceManager.GetObject("ClickToUpload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cqrxs.eu/cqrsrv/cqrjd/Default.aspx;https://ipv4.cqrxs.eu/cqrsrv/cqrjd/Default.aspx;.
        /// </summary>
        internal static string CqrServerUrlToPost {
            get {
                return ResourceManager.GetString("CqrServerUrlToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/chat-ipv6.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.100.254.167;2a05:d011:cdf:3a00:75d:d95d:136e:9e41;2a05:d011:cdf:3a00:726a:e8ec:f5ca:8caa.
        /// </summary>
        internal static string Proxies {
            get {
                return ResourceManager.GetString("Proxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cqrxs.eu;ipv6.cqrxs.eu;ipv4.cqrxs.eu;virginia.area23.at.
        /// </summary>
        internal static string ProxyNames {
            get {
                return ResourceManager.GetString("ProxyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoteConnect {
            get {
                object obj = ResourceManager.GetObject("RemoteConnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cqrxs.eu/cqrsrv/cqrjd/R.aspx;https://ipv4.cqrxs.eu/cqrsrv/cqrjd/R.aspx;https://ipv6.cqrxs.eu/cqrsrv/cqrjd/R.aspx;https://area23.at/net/R.aspx;.
        /// </summary>
        internal static string RemoteIpUrls {
            get {
                return ResourceManager.GetString("RemoteIpUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TransparentFormsIcon {
            get {
                object obj = ResourceManager.GetObject("TransparentFormsIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WinFormAboutDialog {
            get {
                object obj = ResourceManager.GetObject("WinFormAboutDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
