//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EU.CqrXs.Web.WcfTestService.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/EU.CqrXs.Web.WcfTestService.Data")]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private EU.CqrXs.Web.WcfTestService.Data.Author AuthorField;
        
        private int FirstPublishedField;
        
        private string IdField;
        
        private EU.CqrXs.Web.WcfTestService.Data.language LanguageField;
        
        private string[] TagsField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EU.CqrXs.Web.WcfTestService.Data.Author Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstPublished
        {
            get
            {
                return this.FirstPublishedField;
            }
            set
            {
                this.FirstPublishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EU.CqrXs.Web.WcfTestService.Data.language Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/EU.CqrXs.Web.WcfTestService.Data")]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="language", Namespace="http://schemas.datacontract.org/2004/07/EU.CqrXs.Web.WcfTestService.Data")]
    public partial class language : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DisplayNameField;
        
        private string EnglishNameField;
        
        private string ISO2Field;
        
        private string ISO3Field;
        
        private string NameField;
        
        private string NativeNameField;
        
        private string TopLevelDomainField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishName
        {
            get
            {
                return this.EnglishNameField;
            }
            set
            {
                this.EnglishNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISO2
        {
            get
            {
                return this.ISO2Field;
            }
            set
            {
                this.ISO2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISO3
        {
            get
            {
                return this.ISO3Field;
            }
            set
            {
                this.ISO3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NativeName
        {
            get
            {
                return this.NativeNameField;
            }
            set
            {
                this.NativeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopLevelDomain
        {
            get
            {
                return this.TopLevelDomainField;
            }
            set
            {
                this.TopLevelDomainField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICqrService")]
public interface ICqrService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/CreateBook", ReplyAction="http://tempuri.org/ICqrService/CreateBookResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Book CreateBook(EU.CqrXs.Web.WcfTestService.Data.Book value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadBooks", ReplyAction="http://tempuri.org/ICqrService/ReadBooksResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Book[] ReadBooks(string filterText);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadBook", ReplyAction="http://tempuri.org/ICqrService/ReadBookResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Book ReadBook(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/UpdateBook", ReplyAction="http://tempuri.org/ICqrService/UpdateBookResponse")]
    void UpdateBook(string id, EU.CqrXs.Web.WcfTestService.Data.Book value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/DeleteBook", ReplyAction="http://tempuri.org/ICqrService/DeleteBookResponse")]
    void DeleteBook(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadBookAuthor", ReplyAction="http://tempuri.org/ICqrService/ReadBookAuthorResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Author ReadBookAuthor(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/CreateAuthor", ReplyAction="http://tempuri.org/ICqrService/CreateAuthorResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Author CreateAuthor(EU.CqrXs.Web.WcfTestService.Data.Author value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadAuthors", ReplyAction="http://tempuri.org/ICqrService/ReadAuthorsResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Author[] ReadAuthors();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadAuthor", ReplyAction="http://tempuri.org/ICqrService/ReadAuthorResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Author ReadAuthor(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/UpdateAuthor", ReplyAction="http://tempuri.org/ICqrService/UpdateAuthorResponse")]
    void UpdateAuthor(string id, EU.CqrXs.Web.WcfTestService.Data.Author value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/DeleteAuthor", ReplyAction="http://tempuri.org/ICqrService/DeleteAuthorResponse")]
    void DeleteAuthor(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadAuthorBooks", ReplyAction="http://tempuri.org/ICqrService/ReadAuthorBooksResponse")]
    EU.CqrXs.Web.WcfTestService.Data.Book[] ReadAuthorBooks(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/CreateLanguage", ReplyAction="http://tempuri.org/ICqrService/CreateLanguageResponse")]
    EU.CqrXs.Web.WcfTestService.Data.language CreateLanguage(EU.CqrXs.Web.WcfTestService.Data.language value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadLanguages", ReplyAction="http://tempuri.org/ICqrService/ReadLanguagesResponse")]
    EU.CqrXs.Web.WcfTestService.Data.language[] ReadLanguages();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadLanguage", ReplyAction="http://tempuri.org/ICqrService/ReadLanguageResponse")]
    EU.CqrXs.Web.WcfTestService.Data.language ReadLanguage(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/UpdateLanguage", ReplyAction="http://tempuri.org/ICqrService/UpdateLanguageResponse")]
    void UpdateLanguage(string id, EU.CqrXs.Web.WcfTestService.Data.language value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/DeleteLanguage", ReplyAction="http://tempuri.org/ICqrService/DeleteLanguageResponse")]
    void DeleteLanguage(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICqrServiceChannel : ICqrService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CqrServiceClient : System.ServiceModel.ClientBase<ICqrService>, ICqrService
{
    
    public CqrServiceClient()
    {
    }
    
    public CqrServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CqrServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CqrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CqrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book CreateBook(EU.CqrXs.Web.WcfTestService.Data.Book value)
    {
        return base.Channel.CreateBook(value);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book[] ReadBooks(string filterText)
    {
        return base.Channel.ReadBooks(filterText);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book ReadBook(string id)
    {
        return base.Channel.ReadBook(id);
    }
    
    public void UpdateBook(string id, EU.CqrXs.Web.WcfTestService.Data.Book value)
    {
        base.Channel.UpdateBook(id, value);
    }
    
    public void DeleteBook(string id)
    {
        base.Channel.DeleteBook(id);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author ReadBookAuthor(string id)
    {
        return base.Channel.ReadBookAuthor(id);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author CreateAuthor(EU.CqrXs.Web.WcfTestService.Data.Author value)
    {
        return base.Channel.CreateAuthor(value);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author[] ReadAuthors()
    {
        return base.Channel.ReadAuthors();
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author ReadAuthor(string id)
    {
        return base.Channel.ReadAuthor(id);
    }
    
    public void UpdateAuthor(string id, EU.CqrXs.Web.WcfTestService.Data.Author value)
    {
        base.Channel.UpdateAuthor(id, value);
    }
    
    public void DeleteAuthor(string id)
    {
        base.Channel.DeleteAuthor(id);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book[] ReadAuthorBooks(string id)
    {
        return base.Channel.ReadAuthorBooks(id);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.language CreateLanguage(EU.CqrXs.Web.WcfTestService.Data.language value)
    {
        return base.Channel.CreateLanguage(value);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.language[] ReadLanguages()
    {
        return base.Channel.ReadLanguages();
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.language ReadLanguage(string id)
    {
        return base.Channel.ReadLanguage(id);
    }
    
    public void UpdateLanguage(string id, EU.CqrXs.Web.WcfTestService.Data.language value)
    {
        base.Channel.UpdateLanguage(id, value);
    }
    
    public void DeleteLanguage(string id)
    {
        base.Channel.DeleteLanguage(id);
    }
}
