//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EU.CqrXs.Web.WcfTestService.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/EU.CqrXs.Web.WcfTestService.Data")]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private EU.CqrXs.Web.WcfTestService.Data.Author AuthorField;
        
        private int FirstPublishedField;
        
        private string IdField;
        
        private EU.CqrXs.Web.WcfTestService.Data.language LanguageField;
        
        private string[] TagsField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EU.CqrXs.Web.WcfTestService.Data.Author Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstPublished
        {
            get
            {
                return this.FirstPublishedField;
            }
            set
            {
                this.FirstPublishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EU.CqrXs.Web.WcfTestService.Data.language Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/EU.CqrXs.Web.WcfTestService.Data")]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="language", Namespace="http://schemas.datacontract.org/2004/07/EU.CqrXs.Web.WcfTestService.Data")]
    public partial class language : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DisplayNameField;
        
        private string EnglishNameField;
        
        private string ISO2Field;
        
        private string ISO3Field;
        
        private string NameField;
        
        private string NativeNameField;
        
        private string TopLevelDomainField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishName
        {
            get
            {
                return this.EnglishNameField;
            }
            set
            {
                this.EnglishNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISO2
        {
            get
            {
                return this.ISO2Field;
            }
            set
            {
                this.ISO2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISO3
        {
            get
            {
                return this.ISO3Field;
            }
            set
            {
                this.ISO3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NativeName
        {
            get
            {
                return this.NativeNameField;
            }
            set
            {
                this.NativeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopLevelDomain
        {
            get
            {
                return this.TopLevelDomainField;
            }
            set
            {
                this.TopLevelDomainField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICqrService")]
public interface ICqrService
{
    
    // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/CreateBook", ReplyAction="http://tempuri.org/ICqrService/CreateBookResponse")]
    CreateBookResponse CreateBook(CreateBookRequest request);
    
    // CODEGEN: Generating message contract since element name ReadBooksResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadBooks", ReplyAction="http://tempuri.org/ICqrService/ReadBooksResponse")]
    ReadBooksResponse ReadBooks(ReadBooksRequest request);
    
    // CODEGEN: Generating message contract since element name ReadBookResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadBook", ReplyAction="http://tempuri.org/ICqrService/ReadBookResponse")]
    ReadBookResponse ReadBook(ReadBookRequest request);
    
    // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/UpdateBook", ReplyAction="http://tempuri.org/ICqrService/UpdateBookResponse")]
    UpdateBookResponse UpdateBook(UpdateBookRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/DeleteBook", ReplyAction="http://tempuri.org/ICqrService/DeleteBookResponse")]
    void DeleteBook(string id);
    
    // CODEGEN: Generating message contract since element name ReadBookAuthorResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadBookAuthor", ReplyAction="http://tempuri.org/ICqrService/ReadBookAuthorResponse")]
    ReadBookAuthorResponse ReadBookAuthor(ReadBookAuthorRequest request);
    
    // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/CreateAuthor", ReplyAction="http://tempuri.org/ICqrService/CreateAuthorResponse")]
    CreateAuthorResponse CreateAuthor(CreateAuthorRequest request);
    
    // CODEGEN: Generating message contract since element name ReadAuthorsResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadAuthors", ReplyAction="http://tempuri.org/ICqrService/ReadAuthorsResponse")]
    ReadAuthorsResponse ReadAuthors(ReadAuthorsRequest request);
    
    // CODEGEN: Generating message contract since element name ReadAuthorResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadAuthor", ReplyAction="http://tempuri.org/ICqrService/ReadAuthorResponse")]
    ReadAuthorResponse ReadAuthor(ReadAuthorRequest request);
    
    // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/UpdateAuthor", ReplyAction="http://tempuri.org/ICqrService/UpdateAuthorResponse")]
    UpdateAuthorResponse UpdateAuthor(UpdateAuthorRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/DeleteAuthor", ReplyAction="http://tempuri.org/ICqrService/DeleteAuthorResponse")]
    void DeleteAuthor(string id);
    
    // CODEGEN: Generating message contract since element name ReadAuthorBooksResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadAuthorBooks", ReplyAction="http://tempuri.org/ICqrService/ReadAuthorBooksResponse")]
    ReadAuthorBooksResponse ReadAuthorBooks(ReadAuthorBooksRequest request);
    
    // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/CreateLanguage", ReplyAction="http://tempuri.org/ICqrService/CreateLanguageResponse")]
    CreateLanguageResponse CreateLanguage(CreateLanguageRequest request);
    
    // CODEGEN: Generating message contract since element name ReadLanguagesResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadLanguages", ReplyAction="http://tempuri.org/ICqrService/ReadLanguagesResponse")]
    ReadLanguagesResponse ReadLanguages(ReadLanguagesRequest request);
    
    // CODEGEN: Generating message contract since element name ReadLanguageResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/ReadLanguage", ReplyAction="http://tempuri.org/ICqrService/ReadLanguageResponse")]
    ReadLanguageResponse ReadLanguage(ReadLanguageRequest request);
    
    // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/UpdateLanguage", ReplyAction="http://tempuri.org/ICqrService/UpdateLanguageResponse")]
    UpdateLanguageResponse UpdateLanguage(UpdateLanguageRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICqrService/DeleteLanguage", ReplyAction="http://tempuri.org/ICqrService/DeleteLanguageResponse")]
    void DeleteLanguage(string id);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateBookRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBook", Namespace="http://tempuri.org/", Order=0)]
    public CreateBookRequestBody Body;
    
    public CreateBookRequest()
    {
    }
    
    public CreateBookRequest(CreateBookRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateBookRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Book value;
    
    public CreateBookRequestBody()
    {
    }
    
    public CreateBookRequestBody(EU.CqrXs.Web.WcfTestService.Data.Book value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateBookResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBookResponse", Namespace="http://tempuri.org/", Order=0)]
    public CreateBookResponseBody Body;
    
    public CreateBookResponse()
    {
    }
    
    public CreateBookResponse(CreateBookResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateBookResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Book CreateBookResult;
    
    public CreateBookResponseBody()
    {
    }
    
    public CreateBookResponseBody(EU.CqrXs.Web.WcfTestService.Data.Book CreateBookResult)
    {
        this.CreateBookResult = CreateBookResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadBooksRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadBooks", Namespace="http://tempuri.org/", Order=0)]
    public ReadBooksRequestBody Body;
    
    public ReadBooksRequest()
    {
    }
    
    public ReadBooksRequest(ReadBooksRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadBooksRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string filterText;
    
    public ReadBooksRequestBody()
    {
    }
    
    public ReadBooksRequestBody(string filterText)
    {
        this.filterText = filterText;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadBooksResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadBooksResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadBooksResponseBody Body;
    
    public ReadBooksResponse()
    {
    }
    
    public ReadBooksResponse(ReadBooksResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadBooksResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Book[] ReadBooksResult;
    
    public ReadBooksResponseBody()
    {
    }
    
    public ReadBooksResponseBody(EU.CqrXs.Web.WcfTestService.Data.Book[] ReadBooksResult)
    {
        this.ReadBooksResult = ReadBooksResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadBookRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadBook", Namespace="http://tempuri.org/", Order=0)]
    public ReadBookRequestBody Body;
    
    public ReadBookRequest()
    {
    }
    
    public ReadBookRequest(ReadBookRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadBookRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    public ReadBookRequestBody()
    {
    }
    
    public ReadBookRequestBody(string id)
    {
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadBookResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadBookResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadBookResponseBody Body;
    
    public ReadBookResponse()
    {
    }
    
    public ReadBookResponse(ReadBookResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadBookResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Book ReadBookResult;
    
    public ReadBookResponseBody()
    {
    }
    
    public ReadBookResponseBody(EU.CqrXs.Web.WcfTestService.Data.Book ReadBookResult)
    {
        this.ReadBookResult = ReadBookResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateBookRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBook", Namespace="http://tempuri.org/", Order=0)]
    public UpdateBookRequestBody Body;
    
    public UpdateBookRequest()
    {
    }
    
    public UpdateBookRequest(UpdateBookRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateBookRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public EU.CqrXs.Web.WcfTestService.Data.Book value;
    
    public UpdateBookRequestBody()
    {
    }
    
    public UpdateBookRequestBody(string id, EU.CqrXs.Web.WcfTestService.Data.Book value)
    {
        this.id = id;
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateBookResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBookResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateBookResponseBody Body;
    
    public UpdateBookResponse()
    {
    }
    
    public UpdateBookResponse(UpdateBookResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateBookResponseBody
{
    
    public UpdateBookResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadBookAuthorRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadBookAuthor", Namespace="http://tempuri.org/", Order=0)]
    public ReadBookAuthorRequestBody Body;
    
    public ReadBookAuthorRequest()
    {
    }
    
    public ReadBookAuthorRequest(ReadBookAuthorRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadBookAuthorRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    public ReadBookAuthorRequestBody()
    {
    }
    
    public ReadBookAuthorRequestBody(string id)
    {
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadBookAuthorResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadBookAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadBookAuthorResponseBody Body;
    
    public ReadBookAuthorResponse()
    {
    }
    
    public ReadBookAuthorResponse(ReadBookAuthorResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadBookAuthorResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Author ReadBookAuthorResult;
    
    public ReadBookAuthorResponseBody()
    {
    }
    
    public ReadBookAuthorResponseBody(EU.CqrXs.Web.WcfTestService.Data.Author ReadBookAuthorResult)
    {
        this.ReadBookAuthorResult = ReadBookAuthorResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateAuthorRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAuthor", Namespace="http://tempuri.org/", Order=0)]
    public CreateAuthorRequestBody Body;
    
    public CreateAuthorRequest()
    {
    }
    
    public CreateAuthorRequest(CreateAuthorRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateAuthorRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Author value;
    
    public CreateAuthorRequestBody()
    {
    }
    
    public CreateAuthorRequestBody(EU.CqrXs.Web.WcfTestService.Data.Author value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateAuthorResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
    public CreateAuthorResponseBody Body;
    
    public CreateAuthorResponse()
    {
    }
    
    public CreateAuthorResponse(CreateAuthorResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateAuthorResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Author CreateAuthorResult;
    
    public CreateAuthorResponseBody()
    {
    }
    
    public CreateAuthorResponseBody(EU.CqrXs.Web.WcfTestService.Data.Author CreateAuthorResult)
    {
        this.CreateAuthorResult = CreateAuthorResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadAuthorsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAuthors", Namespace="http://tempuri.org/", Order=0)]
    public ReadAuthorsRequestBody Body;
    
    public ReadAuthorsRequest()
    {
    }
    
    public ReadAuthorsRequest(ReadAuthorsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ReadAuthorsRequestBody
{
    
    public ReadAuthorsRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadAuthorsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAuthorsResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadAuthorsResponseBody Body;
    
    public ReadAuthorsResponse()
    {
    }
    
    public ReadAuthorsResponse(ReadAuthorsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadAuthorsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Author[] ReadAuthorsResult;
    
    public ReadAuthorsResponseBody()
    {
    }
    
    public ReadAuthorsResponseBody(EU.CqrXs.Web.WcfTestService.Data.Author[] ReadAuthorsResult)
    {
        this.ReadAuthorsResult = ReadAuthorsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadAuthorRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAuthor", Namespace="http://tempuri.org/", Order=0)]
    public ReadAuthorRequestBody Body;
    
    public ReadAuthorRequest()
    {
    }
    
    public ReadAuthorRequest(ReadAuthorRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadAuthorRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    public ReadAuthorRequestBody()
    {
    }
    
    public ReadAuthorRequestBody(string id)
    {
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadAuthorResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadAuthorResponseBody Body;
    
    public ReadAuthorResponse()
    {
    }
    
    public ReadAuthorResponse(ReadAuthorResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadAuthorResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Author ReadAuthorResult;
    
    public ReadAuthorResponseBody()
    {
    }
    
    public ReadAuthorResponseBody(EU.CqrXs.Web.WcfTestService.Data.Author ReadAuthorResult)
    {
        this.ReadAuthorResult = ReadAuthorResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateAuthorRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAuthor", Namespace="http://tempuri.org/", Order=0)]
    public UpdateAuthorRequestBody Body;
    
    public UpdateAuthorRequest()
    {
    }
    
    public UpdateAuthorRequest(UpdateAuthorRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateAuthorRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public EU.CqrXs.Web.WcfTestService.Data.Author value;
    
    public UpdateAuthorRequestBody()
    {
    }
    
    public UpdateAuthorRequestBody(string id, EU.CqrXs.Web.WcfTestService.Data.Author value)
    {
        this.id = id;
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateAuthorResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateAuthorResponseBody Body;
    
    public UpdateAuthorResponse()
    {
    }
    
    public UpdateAuthorResponse(UpdateAuthorResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateAuthorResponseBody
{
    
    public UpdateAuthorResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadAuthorBooksRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAuthorBooks", Namespace="http://tempuri.org/", Order=0)]
    public ReadAuthorBooksRequestBody Body;
    
    public ReadAuthorBooksRequest()
    {
    }
    
    public ReadAuthorBooksRequest(ReadAuthorBooksRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadAuthorBooksRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    public ReadAuthorBooksRequestBody()
    {
    }
    
    public ReadAuthorBooksRequestBody(string id)
    {
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadAuthorBooksResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAuthorBooksResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadAuthorBooksResponseBody Body;
    
    public ReadAuthorBooksResponse()
    {
    }
    
    public ReadAuthorBooksResponse(ReadAuthorBooksResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadAuthorBooksResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.Book[] ReadAuthorBooksResult;
    
    public ReadAuthorBooksResponseBody()
    {
    }
    
    public ReadAuthorBooksResponseBody(EU.CqrXs.Web.WcfTestService.Data.Book[] ReadAuthorBooksResult)
    {
        this.ReadAuthorBooksResult = ReadAuthorBooksResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateLanguageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLanguage", Namespace="http://tempuri.org/", Order=0)]
    public CreateLanguageRequestBody Body;
    
    public CreateLanguageRequest()
    {
    }
    
    public CreateLanguageRequest(CreateLanguageRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateLanguageRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.language value;
    
    public CreateLanguageRequestBody()
    {
    }
    
    public CreateLanguageRequestBody(EU.CqrXs.Web.WcfTestService.Data.language value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateLanguageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLanguageResponse", Namespace="http://tempuri.org/", Order=0)]
    public CreateLanguageResponseBody Body;
    
    public CreateLanguageResponse()
    {
    }
    
    public CreateLanguageResponse(CreateLanguageResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class CreateLanguageResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.language CreateLanguageResult;
    
    public CreateLanguageResponseBody()
    {
    }
    
    public CreateLanguageResponseBody(EU.CqrXs.Web.WcfTestService.Data.language CreateLanguageResult)
    {
        this.CreateLanguageResult = CreateLanguageResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadLanguagesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadLanguages", Namespace="http://tempuri.org/", Order=0)]
    public ReadLanguagesRequestBody Body;
    
    public ReadLanguagesRequest()
    {
    }
    
    public ReadLanguagesRequest(ReadLanguagesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ReadLanguagesRequestBody
{
    
    public ReadLanguagesRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadLanguagesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadLanguagesResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadLanguagesResponseBody Body;
    
    public ReadLanguagesResponse()
    {
    }
    
    public ReadLanguagesResponse(ReadLanguagesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadLanguagesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.language[] ReadLanguagesResult;
    
    public ReadLanguagesResponseBody()
    {
    }
    
    public ReadLanguagesResponseBody(EU.CqrXs.Web.WcfTestService.Data.language[] ReadLanguagesResult)
    {
        this.ReadLanguagesResult = ReadLanguagesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadLanguageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadLanguage", Namespace="http://tempuri.org/", Order=0)]
    public ReadLanguageRequestBody Body;
    
    public ReadLanguageRequest()
    {
    }
    
    public ReadLanguageRequest(ReadLanguageRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadLanguageRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    public ReadLanguageRequestBody()
    {
    }
    
    public ReadLanguageRequestBody(string id)
    {
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadLanguageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadLanguageResponse", Namespace="http://tempuri.org/", Order=0)]
    public ReadLanguageResponseBody Body;
    
    public ReadLanguageResponse()
    {
    }
    
    public ReadLanguageResponse(ReadLanguageResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class ReadLanguageResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public EU.CqrXs.Web.WcfTestService.Data.language ReadLanguageResult;
    
    public ReadLanguageResponseBody()
    {
    }
    
    public ReadLanguageResponseBody(EU.CqrXs.Web.WcfTestService.Data.language ReadLanguageResult)
    {
        this.ReadLanguageResult = ReadLanguageResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateLanguageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLanguage", Namespace="http://tempuri.org/", Order=0)]
    public UpdateLanguageRequestBody Body;
    
    public UpdateLanguageRequest()
    {
    }
    
    public UpdateLanguageRequest(UpdateLanguageRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class UpdateLanguageRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public string id;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public EU.CqrXs.Web.WcfTestService.Data.language value;
    
    public UpdateLanguageRequestBody()
    {
    }
    
    public UpdateLanguageRequestBody(string id, EU.CqrXs.Web.WcfTestService.Data.language value)
    {
        this.id = id;
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UpdateLanguageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLanguageResponse", Namespace="http://tempuri.org/", Order=0)]
    public UpdateLanguageResponseBody Body;
    
    public UpdateLanguageResponse()
    {
    }
    
    public UpdateLanguageResponse(UpdateLanguageResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UpdateLanguageResponseBody
{
    
    public UpdateLanguageResponseBody()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICqrServiceChannel : ICqrService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CqrServiceClient : System.ServiceModel.ClientBase<ICqrService>, ICqrService
{
    
    public CqrServiceClient()
    {
    }
    
    public CqrServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CqrServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CqrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CqrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateBookResponse ICqrService.CreateBook(CreateBookRequest request)
    {
        return base.Channel.CreateBook(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book CreateBook(EU.CqrXs.Web.WcfTestService.Data.Book value)
    {
        CreateBookRequest inValue = new CreateBookRequest();
        inValue.Body = new CreateBookRequestBody();
        inValue.Body.value = value;
        CreateBookResponse retVal = ((ICqrService)(this)).CreateBook(inValue);
        return retVal.Body.CreateBookResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadBooksResponse ICqrService.ReadBooks(ReadBooksRequest request)
    {
        return base.Channel.ReadBooks(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book[] ReadBooks(string filterText)
    {
        ReadBooksRequest inValue = new ReadBooksRequest();
        inValue.Body = new ReadBooksRequestBody();
        inValue.Body.filterText = filterText;
        ReadBooksResponse retVal = ((ICqrService)(this)).ReadBooks(inValue);
        return retVal.Body.ReadBooksResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadBookResponse ICqrService.ReadBook(ReadBookRequest request)
    {
        return base.Channel.ReadBook(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book ReadBook(string id)
    {
        ReadBookRequest inValue = new ReadBookRequest();
        inValue.Body = new ReadBookRequestBody();
        inValue.Body.id = id;
        ReadBookResponse retVal = ((ICqrService)(this)).ReadBook(inValue);
        return retVal.Body.ReadBookResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateBookResponse ICqrService.UpdateBook(UpdateBookRequest request)
    {
        return base.Channel.UpdateBook(request);
    }
    
    public void UpdateBook(string id, EU.CqrXs.Web.WcfTestService.Data.Book value)
    {
        UpdateBookRequest inValue = new UpdateBookRequest();
        inValue.Body = new UpdateBookRequestBody();
        inValue.Body.id = id;
        inValue.Body.value = value;
        UpdateBookResponse retVal = ((ICqrService)(this)).UpdateBook(inValue);
    }
    
    public void DeleteBook(string id)
    {
        base.Channel.DeleteBook(id);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadBookAuthorResponse ICqrService.ReadBookAuthor(ReadBookAuthorRequest request)
    {
        return base.Channel.ReadBookAuthor(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author ReadBookAuthor(string id)
    {
        ReadBookAuthorRequest inValue = new ReadBookAuthorRequest();
        inValue.Body = new ReadBookAuthorRequestBody();
        inValue.Body.id = id;
        ReadBookAuthorResponse retVal = ((ICqrService)(this)).ReadBookAuthor(inValue);
        return retVal.Body.ReadBookAuthorResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateAuthorResponse ICqrService.CreateAuthor(CreateAuthorRequest request)
    {
        return base.Channel.CreateAuthor(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author CreateAuthor(EU.CqrXs.Web.WcfTestService.Data.Author value)
    {
        CreateAuthorRequest inValue = new CreateAuthorRequest();
        inValue.Body = new CreateAuthorRequestBody();
        inValue.Body.value = value;
        CreateAuthorResponse retVal = ((ICqrService)(this)).CreateAuthor(inValue);
        return retVal.Body.CreateAuthorResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadAuthorsResponse ICqrService.ReadAuthors(ReadAuthorsRequest request)
    {
        return base.Channel.ReadAuthors(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author[] ReadAuthors()
    {
        ReadAuthorsRequest inValue = new ReadAuthorsRequest();
        inValue.Body = new ReadAuthorsRequestBody();
        ReadAuthorsResponse retVal = ((ICqrService)(this)).ReadAuthors(inValue);
        return retVal.Body.ReadAuthorsResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadAuthorResponse ICqrService.ReadAuthor(ReadAuthorRequest request)
    {
        return base.Channel.ReadAuthor(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Author ReadAuthor(string id)
    {
        ReadAuthorRequest inValue = new ReadAuthorRequest();
        inValue.Body = new ReadAuthorRequestBody();
        inValue.Body.id = id;
        ReadAuthorResponse retVal = ((ICqrService)(this)).ReadAuthor(inValue);
        return retVal.Body.ReadAuthorResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateAuthorResponse ICqrService.UpdateAuthor(UpdateAuthorRequest request)
    {
        return base.Channel.UpdateAuthor(request);
    }
    
    public void UpdateAuthor(string id, EU.CqrXs.Web.WcfTestService.Data.Author value)
    {
        UpdateAuthorRequest inValue = new UpdateAuthorRequest();
        inValue.Body = new UpdateAuthorRequestBody();
        inValue.Body.id = id;
        inValue.Body.value = value;
        UpdateAuthorResponse retVal = ((ICqrService)(this)).UpdateAuthor(inValue);
    }
    
    public void DeleteAuthor(string id)
    {
        base.Channel.DeleteAuthor(id);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadAuthorBooksResponse ICqrService.ReadAuthorBooks(ReadAuthorBooksRequest request)
    {
        return base.Channel.ReadAuthorBooks(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.Book[] ReadAuthorBooks(string id)
    {
        ReadAuthorBooksRequest inValue = new ReadAuthorBooksRequest();
        inValue.Body = new ReadAuthorBooksRequestBody();
        inValue.Body.id = id;
        ReadAuthorBooksResponse retVal = ((ICqrService)(this)).ReadAuthorBooks(inValue);
        return retVal.Body.ReadAuthorBooksResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateLanguageResponse ICqrService.CreateLanguage(CreateLanguageRequest request)
    {
        return base.Channel.CreateLanguage(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.language CreateLanguage(EU.CqrXs.Web.WcfTestService.Data.language value)
    {
        CreateLanguageRequest inValue = new CreateLanguageRequest();
        inValue.Body = new CreateLanguageRequestBody();
        inValue.Body.value = value;
        CreateLanguageResponse retVal = ((ICqrService)(this)).CreateLanguage(inValue);
        return retVal.Body.CreateLanguageResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadLanguagesResponse ICqrService.ReadLanguages(ReadLanguagesRequest request)
    {
        return base.Channel.ReadLanguages(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.language[] ReadLanguages()
    {
        ReadLanguagesRequest inValue = new ReadLanguagesRequest();
        inValue.Body = new ReadLanguagesRequestBody();
        ReadLanguagesResponse retVal = ((ICqrService)(this)).ReadLanguages(inValue);
        return retVal.Body.ReadLanguagesResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReadLanguageResponse ICqrService.ReadLanguage(ReadLanguageRequest request)
    {
        return base.Channel.ReadLanguage(request);
    }
    
    public EU.CqrXs.Web.WcfTestService.Data.language ReadLanguage(string id)
    {
        ReadLanguageRequest inValue = new ReadLanguageRequest();
        inValue.Body = new ReadLanguageRequestBody();
        inValue.Body.id = id;
        ReadLanguageResponse retVal = ((ICqrService)(this)).ReadLanguage(inValue);
        return retVal.Body.ReadLanguageResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateLanguageResponse ICqrService.UpdateLanguage(UpdateLanguageRequest request)
    {
        return base.Channel.UpdateLanguage(request);
    }
    
    public void UpdateLanguage(string id, EU.CqrXs.Web.WcfTestService.Data.language value)
    {
        UpdateLanguageRequest inValue = new UpdateLanguageRequest();
        inValue.Body = new UpdateLanguageRequestBody();
        inValue.Body.id = id;
        inValue.Body.value = value;
        UpdateLanguageResponse retVal = ((ICqrService)(this)).UpdateLanguage(inValue);
    }
    
    public void DeleteLanguage(string id)
    {
        base.Channel.DeleteLanguage(id);
    }
}
